### ISSUE TITLE
where is caffe-action

### ISSUE THREAD

**Issue by Aionrichman** [LuoweiZhou/anet2016-cuhk-feature#2]
“git submodule update --remote” get nothing

**Comment by LuoweiZhou** [comment]
Please refer to the original repo for installation instructions. https://github.com/yjxiong/anet2016-cuhk

**Comment by Aionrichman** [comment]
> Please refer to the original repo for installation instructions. https://github.com/yjxiong/anet2016-cuhk

thx~
